    /**
     * Desenvolvido por Obel.
     * WARNING: Do NOT modify this code. 
     * 
     */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Cliente;
import Classes.Dados;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OBEL
 */
public class frmClientes extends javax.swing.JInternalFrame {
private Dados clsdados;
private int clienteatual = 0;
private boolean cmdNovo = false;
private DefaultTableModel Usertable;


public void setDados(Dados clsdados){
    this.clsdados = clsdados;
}
    public frmClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodcliente = new javax.swing.JTextField();
        txtnomedocliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmdproximo = new javax.swing.JButton();
        cmdultimo = new javax.swing.JButton();
        cmdprimeiro = new javax.swing.JButton();
        cmdanterior = new javax.swing.JButton();
        cmdalterar = new javax.swing.JButton();
        cmdnovo = new javax.swing.JButton();
        cmdsalvar = new javax.swing.JButton();
        cmddeletar = new javax.swing.JButton();
        cmdcancelar = new javax.swing.JButton();
        cmdpesquisar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mtable = new javax.swing.JTable();
        txtsobrenomedocliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        caldata = new com.toedter.calendar.JDateChooser();
        calnasc = new com.toedter.calendar.JDateChooser();
        txttelefone = new javax.swing.JTextField();
        cmbidentificacao = new javax.swing.JComboBox<>();
        cmbcidade = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Clientes:");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Cod. Cliente:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Sobre Nome:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Identificação:");

        txtcodcliente.setEnabled(false);
        txtcodcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodclienteActionPerformed(evt);
            }
        });

        txtnomedocliente.setEnabled(false);
        txtnomedocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomedoclienteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cadastro de Clientes");
        jLabel7.setToolTipText("");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        cmdproximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ir32x32.png"))); // NOI18N
        cmdproximo.setToolTipText("Proximo Cadastro");
        cmdproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdproximoActionPerformed(evt);
            }
        });

        cmdultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duploir32x32.png"))); // NOI18N
        cmdultimo.setToolTipText("Ultimo Cadastro");
        cmdultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdultimoActionPerformed(evt);
            }
        });

        cmdprimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duplovoltar32x32.png"))); // NOI18N
        cmdprimeiro.setToolTipText("Primeiro Cadastro");
        cmdprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdprimeiroActionPerformed(evt);
            }
        });

        cmdanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar32x32.png"))); // NOI18N
        cmdanterior.setToolTipText("Cadastro Anterior");
        cmdanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdanteriorActionPerformed(evt);
            }
        });

        cmdalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/escrever32x32.png"))); // NOI18N
        cmdalterar.setToolTipText("Editar Cadastro");
        cmdalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdalterarActionPerformed(evt);
            }
        });

        cmdnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais32x32.png"))); // NOI18N
        cmdnovo.setToolTipText("Novo Cadastro");
        cmdnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdnovoActionPerformed(evt);
            }
        });

        cmdsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar32x32.png"))); // NOI18N
        cmdsalvar.setToolTipText("Salvar Cadastro");
        cmdsalvar.setEnabled(false);
        cmdsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalvarActionPerformed(evt);
            }
        });

        cmddeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/deletar32x32.png"))); // NOI18N
        cmddeletar.setToolTipText("Pesquisar Cadastro");
        cmddeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeletarActionPerformed(evt);
            }
        });

        cmdcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar32x32.png"))); // NOI18N
        cmdcancelar.setToolTipText("Editar Cadastro");
        cmdcancelar.setEnabled(false);
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });

        cmdpesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar32x32.png"))); // NOI18N
        cmdpesquisar1.setToolTipText("Pesquisar Cadastro");
        cmdpesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpesquisar1ActionPerformed(evt);
            }
        });

        Mtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Mtable);

        txtsobrenomedocliente.setEnabled(false);
        txtsobrenomedocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsobrenomedoclienteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("  Data:");

        txtendereco.setEnabled(false);
        txtendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenderecoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Endereço:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("      Telefone:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("D-Nasc:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel10.setText("E-mail:");

        txtemail.setEnabled(false);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setText("Cidade:");

        txttelefone.setEnabled(false);
        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });

        cmbidentificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione ID", "CPF", "CNPJ", "Carteira de Indentidade" }));
        cmbidentificacao.setEnabled(false);
        cmbidentificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbidentificacaoActionPerformed(evt);
            }
        });

        cmbcidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Cidade", "Vitoria", "Vila Velha", "Serra", "Guaraparir", "Pedra Azul", "Domingos Martins", "Laranja da Terra" }));
        cmbcidade.setEnabled(false);
        cmbcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 193, Short.MAX_VALUE)
                        .addComponent(cmdprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmddeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdpesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtendereco))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel5)
                                        .addGap(10, 10, 10)
                                        .addComponent(txttelefone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(calnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtemail)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbcidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsobrenomedocliente)
                            .addComponent(txtnomedocliente)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcodcliente)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbidentificacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caldata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(caldata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnomedocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtsobrenomedocliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(txtcodcliente)
                            .addComponent(cmbidentificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addGap(56, 56, 56)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtendereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11)
                        .addComponent(txttelefone)
                        .addComponent(cmbcidade, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdproximo)
                    .addComponent(cmdultimo)
                    .addComponent(cmdprimeiro)
                    .addComponent(cmdanterior)
                    .addComponent(cmdsalvar)
                    .addComponent(cmddeletar)
                    .addComponent(cmdnovo)
                    .addComponent(cmdalterar)
                    .addComponent(cmdcancelar)
                    .addComponent(cmdpesquisar1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodclienteActionPerformed

    private void cmdnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdnovoActionPerformed
        // TODO add your handling code here:
        cmdprimeiro.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdproximo.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdnovo.setEnabled(false);
        cmdalterar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdsalvar.setEnabled(true);
        cmddeletar.setEnabled(false);
        
        txtcodcliente.setEnabled(true);
        cmbcidade.setEnabled(true);
        txtnomedocliente.setEnabled(true);
        txtsobrenomedocliente.setEnabled(true);
        txtendereco.setEnabled(true);
        txtemail.setEnabled(true);
        calnasc.setEnabled(true);
        
        
        txtcodcliente.setText("");
        txtnomedocliente.setText("");
        txtsobrenomedocliente.setText("");
        txtendereco.setText("");
        txttelefone.setText("");
        cmbcidade.setSelectedIndex(0);
        cmbidentificacao.setSelectedIndex(0);
        txtemail.setText("");
        calnasc.setDate(new Date());
        caldata.setDate(new Date());
        
        
        cmdNovo=true;
        
        txtcodcliente.requestFocusInWindow();
        
        CarregarTable();       
        
    }//GEN-LAST:event_cmdnovoActionPerformed

    private void cmdalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdalterarActionPerformed
        // TODO add your handling code here:
        cmdprimeiro.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdproximo.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdnovo.setEnabled(false);
        cmdalterar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdsalvar.setEnabled(true);
        cmddeletar.setEnabled(false);
        
        cmbcidade.setEnabled(true);
        cmbidentificacao.setEnabled(true);
        txtnomedocliente.setEnabled(true);
        txtsobrenomedocliente.setEnabled(true);
        txtendereco.setEnabled(true);
        txttelefone.setEnabled(true);
        txtemail.setEnabled(true);
        calnasc.setEnabled(true);
         
        cmdNovo=false;
        
        cmbcidade.requestFocusInWindow();
        
        CarregarTable();
    }//GEN-LAST:event_cmdalterarActionPerformed

    private void cmdsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalvarActionPerformed

        // Validando Campos no Formulario de Cadastro
        
        if (txtcodcliente.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Favor digitar o codigo de cliente valido");
            txtcodcliente.requestFocusInWindow();
            return;
        }
        if (cmbcidade.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Favor digitar um numero de telefone valido");
            cmbcidade.requestFocusInWindow();
            return;
        }
        if (cmbidentificacao.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Favor digitar um cidade valido");
            cmbcidade.requestFocusInWindow();
            return;
        }
        if (txtemail.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Favor digitar o e-mail valido");
            txtemail.requestFocusInWindow();
            return;
            
        }
        
        if (txtsobrenomedocliente.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Favor digitar sobrenome do cliente valido");
            txtsobrenomedocliente.requestFocusInWindow();
            return;
        }       
        if (calnasc.getDate().before(new Date())){
            JOptionPane.showMessageDialog(rootPane, "O cliente nao pode ter a data de nascimento igual a data atual");
            calnasc.requestFocusInWindow();
            return;
        }
        if (caldata.getDate().before(new Date())){
            JOptionPane.showMessageDialog(rootPane, "O cliente nao pode ter a data atual igual a data de nascimento");
            calnasc.requestFocusInWindow();
            return;
        }
        
        int poslinha = clsdados.LinhaProdutos(txtcodcliente.getText());
        if (cmdNovo){       
            if (poslinha != -1){
            JOptionPane.showMessageDialog(rootPane, " Esse cadastro de usuario já existe no banco de dados");
            txtcodcliente.requestFocusInWindow();
            return;
            
        }
        }
        else{
            if(poslinha == -1){
                JOptionPane.showMessageDialog(rootPane, " Esse cadastro de cliente não existe no banco de dados");
                txtcodcliente.requestFocusInWindow();
                return;
                
            }
        }
        Cliente Mcliente;
    Mcliente = new Cliente(txtcodcliente.getText(),
            cmbcidade.getSelectedIndex(),            
            txtnomedocliente.getText(),
            txtsobrenomedocliente.getText(),
            txtendereco.getText(),
            txttelefone.getText(),
            cmbidentificacao.getSelectedIndex(),
            caldata.getDate(),
            calnasc.getDate(),
            txtemail.getText()
    );
        
        String msg;
        if (cmdNovo){
            msg = clsdados.Cadcliente(Mcliente);
        }else{
            msg = clsdados.EditarCliente(Mcliente, poslinha);
        }
        JOptionPane.showMessageDialog(rootPane, msg);
        CarregarTable();
                
        // Codigo do botão salvar formulario usuarios
        
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdnovo.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmdcancelar.setEnabled(false);
        cmdsalvar.setEnabled(false);
        cmddeletar.setEnabled(true);
        
        txtcodcliente.setEnabled(false);
        cmbcidade.setEnabled(false);
        cmbidentificacao.setEnabled(false);
        txtnomedocliente.setEnabled(false);
        txtsobrenomedocliente.setEnabled(false);
        txtendereco.setEnabled(false);
        txttelefone.setEnabled(false);
        txtemail.setEnabled(false);
        calnasc.setEnabled(false);
        
    }//GEN-LAST:event_cmdsalvarActionPerformed

    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed
        // Codigo do botão cancelar
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdnovo.setEnabled(true);
        cmdalterar.setEnabled(true);
        cmdcancelar.setEnabled(false);
        cmdsalvar.setEnabled(false);
        cmddeletar.setEnabled(true);
        
        txtcodcliente.setEnabled(false);
        cmbcidade.setEnabled(false);
        cmbidentificacao.setEnabled(false);
        txtnomedocliente.setEnabled(false);
        txtsobrenomedocliente.setEnabled(false);
        txtendereco.setEnabled(false);
        txttelefone.setEnabled(false);
        txtemail.setEnabled(false);
        calnasc.setEnabled(false);
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
     visualizarCadastros();
     CarregarTable();
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void cmdprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdprimeiroActionPerformed
        // Codigo de botão primeiro do formulario de ususarios
        
        clienteatual = 0;
        visualizarCadastros();
    }//GEN-LAST:event_cmdprimeiroActionPerformed

    private void cmdultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdultimoActionPerformed
        // Ultimo metodo para chamar o contador
        clienteatual = clsdados.NProdutos()-1;
        visualizarCadastros();
    }//GEN-LAST:event_cmdultimoActionPerformed

    private void cmdproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdproximoActionPerformed
        // Proximo incremento
        clienteatual ++;
        if (clienteatual == clsdados.NProdutos()){
            clienteatual=0;
        }
        visualizarCadastros();
    }//GEN-LAST:event_cmdproximoActionPerformed

    private void cmdanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdanteriorActionPerformed
        // incremento anterior
        clienteatual --;
        if (clienteatual == -1){
            clienteatual = clsdados.NProdutos()-1;
            
        }
        visualizarCadastros();
        
        
    }//GEN-LAST:event_cmdanteriorActionPerformed

    private void cmddeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeletarActionPerformed
        // Metodo para deletar
        int Del;
        Del = JOptionPane.showConfirmDialog(rootPane, "Deseja deletar o cadastro ?");
        if(Del !=0){
            return;
        }
        String msg;
        msg = clsdados.DeletarUsuario(clienteatual);
        JOptionPane.showMessageDialog(rootPane, msg);
        clienteatual=0;
        visualizarCadastros();
        CarregarTable();
    }//GEN-LAST:event_cmddeletarActionPerformed

    private void cmdpesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpesquisar1ActionPerformed
        // Metodo Pesquisar
        String cliente = JOptionPane.showInputDialog("Digite o codigo do cliente para realizar sua pesquisa");
        if (cliente.equals("")){
            return;
        }
        int posL = clsdados.LinhaProdutos(cliente);
        if (posL ==  -1){
            JOptionPane.showMessageDialog(rootPane, "Não foi possivel localizar esse cadastro no banco de dados");
            return;
        }
        clienteatual=posL;
        visualizarCadastros();
       
    }//GEN-LAST:event_cmdpesquisar1ActionPerformed

    private void txtsobrenomedoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsobrenomedoclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsobrenomedoclienteActionPerformed

    private void txtnomedoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomedoclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomedoclienteActionPerformed

    private void txtenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenderecoActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneActionPerformed

    private void cmbidentificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbidentificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbidentificacaoActionPerformed

    private void cmbcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcidadeActionPerformed
    private void visualizarCadastros(){
        txtcodcliente.setText(clsdados.getClientes()[clienteatual].getIdCliente());

        txtnomedocliente.setText(clsdados.getClientes()[clienteatual].getNome());
        txtsobrenomedocliente.setText(clsdados.getClientes()[clienteatual].getSobnome());
        txttelefone.setText(clsdados.getClientes()[clienteatual].getTelefone());
        txtendereco.setText(clsdados.getClientes()[clienteatual].getEndereco());
        txtemail.setText(clsdados.getClientes()[clienteatual].getEmail());
        cmbcidade.setSelectedIndex( clsdados.getClientes()[clienteatual].getCidade());
        cmbidentificacao.setSelectedIndex(clsdados.getClientes()[clienteatual].getIndent());
        caldata.setDate(clsdados.getClientes()[clienteatual].getDataVenda());
        calnasc.setDate(clsdados.getClientes()[clienteatual].getDataNasc());
        
       
    }
    
    private void CarregarTable(){
        String titulocabecalho[]={"Cod-Cliente", "Ident", "Data", "Nome", "Sobrenome", "End", "Tel", "Data-Nasc.", "Cidade", "E-mail"};
        String RegCadastro[] = new String [10];
        Usertable=new DefaultTableModel(null,titulocabecalho);
        for(int i=0;i<clsdados.NProdutos();i++){
            RegCadastro[0]=clsdados.getClientes()[i].getIdCliente();
            RegCadastro[1]=Id(clsdados.getClientes()[i].getIndent());
            RegCadastro[2]="" + clsdados.getClientes()[i].getDataVenda();
            RegCadastro[3]=clsdados.getClientes()[i].getNome();
            RegCadastro[4]=clsdados.getClientes()[i].getSobnome();
            RegCadastro[5]=clsdados.getClientes()[i].getEndereco();
            RegCadastro[6]=clsdados.getProdutos()[i].getObservacao();
            RegCadastro[7]=clsdados.getProdutos()[i].getObservacao();
            RegCadastro[8]=clsdados.getProdutos()[i].getObservacao();
            RegCadastro[9]=clsdados.getProdutos()[i].getObservacao();
            
            Usertable.addRow(RegCadastro);
        }
        Mtable.setModel(Usertable);
    }
    private String Id (int ident){
        switch(ident){
            case 0: return "CPF";
            case 1: return "CNPJ";
            case 2: return "Carteira de Identidade";
            default: return "Sem Id";
        }
    }
    
    private String Cidade (int idCidade){
        switch(idCidade){
            case 0: return "0%";
            case 1: return "10%";
            case 2: return "15%";
            case 3: return "20%";
            default: return "Sem Cidade";
            
        
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Mtable;
    private com.toedter.calendar.JDateChooser caldata;
    private com.toedter.calendar.JDateChooser calnasc;
    private javax.swing.JComboBox<String> cmbcidade;
    private javax.swing.JComboBox<String> cmbidentificacao;
    private javax.swing.JButton cmdalterar;
    private javax.swing.JButton cmdanterior;
    private javax.swing.JButton cmdcancelar;
    private javax.swing.JButton cmddeletar;
    private javax.swing.JButton cmdnovo;
    private javax.swing.JButton cmdpesquisar1;
    private javax.swing.JButton cmdprimeiro;
    private javax.swing.JButton cmdproximo;
    private javax.swing.JButton cmdsalvar;
    private javax.swing.JButton cmdultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcodcliente;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnomedocliente;
    private javax.swing.JTextField txtsobrenomedocliente;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
